language: php

php:
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer require --dev

install:
  - travis_retry composer install


script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/behat --config behat.yml
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run --config-file ./.php_cs

after_script:
  - ls .reports
  - ./vendor/bin/coveralls -v  --config .coveralls.yml

notifications:
  email:
  - and-rey2@yandex.ru

branches:
  only:
    - dev