docs_dir: doc/book/ru
pages:
    - index.md
    - 'Руководство OTWorkflow':
      - 'Оглавление': 'manual/manual.md'
      - 'Концепция OTWorkflow': 'manual/understanding_otworkflow/workflow_concepts.md'
site_name: workflow
site_description: 'Движок workflow'
repo_url: 'https://github.com/old-town/old-town-workflow'
copyright: 'Copyright (c) 2016 <a href="https://github.com/old-town/">OldTown</a>'